server:
  port: 8080

# 若要访问端点信息，需要配置用户名和密码
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookcard?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    username: root
    password: adminroot
    maxActive: 500
  mail:
    host: smtp.qq.com #SMTP服务器地址
    username:  346484458@qq.com #登陆账号
    password: cqkjmgrqfhabbied #登陆密码（或授权码）
    properties:
      from: 346484458@qq.com #邮件发信人（即真实邮箱）
  thymeleaf:
    cache: false
    prefix: classpath:/views/
  servlet:
    multipart:
      max-file-size: 10MB #限制单个文件大小
      max-request-size: 50MB #限制请求总量
  logging:
    level:
      org:
        springframework:
          security: INFO

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

